#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

SRC_PATTERN="\.y(a?ml)$"
if git diff --cached --name-only | grep --quiet -E "$SRC_PATTERN"
then
  echo "Not building anything -- moved generation to Standata"
fi

npx lint-staged
