#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

SRC_PATTERN="\.y(a?ml)$"
YAML_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "$SRC_PATTERN")
if [ -n "$YAML_FILES" ]; then
    echo "YAML files detected, running yamllint..."
    echo "$YAML_FILES" | xargs -r yamllint
fi

npx lint-staged
